### ISSUE TITLE
Commands hang/don't execute

### ISSUE THREAD

**Issue by Jont828** [altdesktop/playerctl#109]
When I try to type `playerctl pause`, `playerctl play`, or `playerctl status`, the command just hangs and doesn't execute. Playerctl lists Spotify when I run `playerctl -l`, though.

**Comment by acrisci** [comment]
Try this and see if it hangs:

```
dbus-send --print-reply --type=method_call --dest=org.mpris.MediaPlayer2.vlc /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
```

**Comment by cphyc** [comment]
Hi, I'm having the same trouble. When I run `playerctl -p spotify play-pause`, the command hangs for a while before returning the following error:
```
$ playerctl -p spotify play-pause
Could not execute command: Timeout was reached
```
If I try the `dbus-send` command, I get:
```
dbus-send --print-reply --type=method_call --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
```
---
System configuration: Arch Linux

**Comment by mpgarate** [comment]
I am experiencing this behavior as well on Ubuntu 19.04 with spotify installed via snap.

**Comment by acrisci** [comment]
All I know about Spotify is in the [troubleshooting](https://github.com/acrisci/playerctl#troubleshooting) section. Snaps or flatpaks may need extra configuration to allow access to dbus.

I can't fix Spotify bugs because the code is not open source. Contact Spotify customer support.

**Comment by jorp** [comment]
`$ playerctl -p spotify play-pause` is working fine for me without hanging, but I'm experiencing the described behavior when trying with firefox.

**Comment by GaugeK** [comment]
After enabling `media.hardwaremediakeys.enabled` in firefox, playerctl toggles pause instantly, but it hangs for a while after that and says the timeout was reached. No idea why it works then freezes.

**Comment by acrisci** [comment]
For an example letter to spotify customer support, see [here](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md).

For the firefox issue, see #179
