### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by acrisci** [altdesktop/playerctl#113]
It would be easier to debug some issues on this tracker if playerctl had debug logging I could get from people. Enable debug logging with an environment variable.

**Comment by MarkusGordathian** [comment]
Should debug messages be printed to stderr or should users be required to specify a file path?

What about using an argument (probably `-V` as `-v` is already taken) to enable debug logging instead of an environment variable?

**Comment by acrisci** [comment]
> Should debug messages be printed to stderr or should users be required to specify a file path?

Use stderr. Shell redirects can be used for a file path.

> What about using an argument (probably -V as -v is already taken) to enable debug logging instead of an environment variable?

I was going to use GLib logging for this since we have that dependency which does it with environment variables I think. But a command line option is fine too.

https://developer.gnome.org/glib/stable/glib-Message-Logging.html

**Comment by MarkusGordathian** [comment]
Now that I've read into GLib's logging more, I understand that a command line option isn't needed, as messages, warnings, and errors are printed by default. I'll forget about the command line option.

**Comment by MarkusGordathian** [comment]
Should the already-existing error logging be converted to GLib's structured log functions? I think it would be messy to have errors logged via `g_printerr()` and other debug information through the structured functions.

**Comment by acrisci** [comment]
Any info a user is intended to see as a normal part of the operation of the program shouldn't be a structured log. For example "no players found", because that's not an application error, but a state that playerctl is intended to be in. Any error that is bubbled up and handled should be the same. Many of the errors can happen because of players that don't implement the spec properly, which is not a playerctl application error.

The intent of the debug logging is to show more info about why the error occurred to someone who is debugging what went wrong later.

**Comment by MarkusGordathian** [comment]
Apologies for the radio silence on this. October has gotten me back in the contributing mood, and I've started working on this issue again.
