### ISSUE TITLE
Don't work with spotify

### ISSUE THREAD

**Issue by hrqmonteiro** [altdesktop/playerctl#121]
Simply can't recognize spotify, no matter what i do it still goes:

[hrq@motherbase ~]$ playerctl -l
[hrq@motherbase ~]$ No players were found

I even tried everything from other issues around here and another places

It works with every other single player but not with spotify

**Comment by acrisci** [comment]
Contact Spotify customer support.

**Comment by hrqmonteiro** [comment]
Well, alright, then..

**Comment by philippeboyd** [comment]
Works good with Spotify... or, rather, worked.
Metadatas are now empty on all tracks (Artist, Album, Title, etc)

```
spotify mpris:trackid             spotify:track:78wMD0pLwum3Xmm76VMQel
spotify mpris:length              248176000
spotify mpris:artUrl              
spotify xesam:album               
spotify xesam:albumArtist         
spotify xesam:artist              
spotify xesam:autoRating          0.0
spotify xesam:discNumber          0
spotify xesam:title               
spotify xesam:trackNumber         0
spotify xesam:url                 https://open.spotify.com/track/78wMD0pLwum3Xmm76VMQel
```

**Comment by ericonr** [comment]
You can use something like `spotifyd` as the Spotify device. It reports all the information and can be controlled by playerctl commands.

**Comment by acrisci** [comment]
I'm serious about contacting Spotify support btw. I don't think people are doing it 🧐.

Also see the [troubleshooting](https://github.com/altdesktop/playerctl#troubleshooting) section. You need to have dbus variables such as `DBUS_SESSION_BUS_ADDRESS` set for it to work.

**Comment by AdamSLevy** [comment]
if you are launching spotify directly from the CLI and not using the desktop entry then you'll probably have issues.

Try launching spotify from the cli using `dex /usr/share/applications/spotify.desktop`

**Comment by AnySomebody1** [comment]
I don't have any problems with Spotify at all, neither with the Desktop launcher nor with the bin itself.

**Comment by acrisci** [comment]
For an example letter to spotify customer support, see [here](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md).
