### ISSUE TITLE
Python gi.repository fails to import Playerctl

### ISSUE THREAD

**Issue by Rsantct** [altdesktop/playerctl#123]
Hi,

It seems that **Playerclt** is missing under newer Debian's **gi repository**

DEBIAN fails:
**python3-gi**/testing,now **3.30.4-1** amd64 [instalado, automático]
**libgirepository-1.0-1**/testing,now **1.58.3-2** amd64 [instalado, automático]
```
$ python3
Python 3.7.2+ (default, Feb  2 2019, 14:31:48) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Playerctl', '1.0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Playerctl not available
>>> from gi.repository import Playerctl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 133, in load_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name Playerctl, introspection typelib not found
>>> 
```

UBUNTU 18.04 works
**python3-gi**/bionic,now **3.26.1-2** amd64 [instalado, automático]
**libgirepository-1.0-1**/bionic,now **1.56.1-1** amd64 [instalado, automático]
```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version('Playerctl', '1.0')
>>> from gi.repository import Playerctl
>>> 
```

**Comment by acrisci** [comment]
I will try to help you the best I can before getting the maintainers involved.

It looks like they split the the playerctl package into three parts. One for the binary, one for the C library, and one for the gir.

Do you have these packages?

https://packages.debian.org/sid/gir1.2-playerctl-2.0

https://packages.debian.org/sid/libplayerctl-dev

You'll need the files within these packages for this to work correctly. In particular, you need the `.typelib` file.

Also note that the gir version is now at 2.0 and you are requiring 1.0.

**Comment by Rsantct** [comment]
Hi, 

I will adapt my scripts to 2.0 as per your indications.

Also I have discover the excellent new binary feature **--follow** that is very useful, so I have rewrote temporally my scripts to use the binary :-)

Thank you very much for your help and congratulations for the new playerctl 2.0 release !

**Comment by acrisci** [comment]
:+1:

**Comment by himynameisulpa** [comment]
What packages do I need to install when I am on Solus?

**Comment by mohammedbabiker** [comment]
Use gi.require_version('Playerctl', '2.0')
