### ISSUE TITLE
Access most recent player

### ISSUE THREAD

**Issue by eater** [altdesktop/playerctl#128]
I see that "follow mode" can track the most recently used player. Is there a way to find the most recently used player outside of follow mode, in the CLI or the API?

Or what would be the best way to send a `play-pause` to the most recent player? Thanks.

**Comment by acrisci** [comment]
I don't know how this could be done without a persistent process. The most recent player is determined by which one had activity last on dbus.

You could make a daemon with the library to always run and save activity to a database. Maybe just the name of the most recent player in a temp file.

Other than that I don't know.

**Comment by eater** [comment]
Makes sense, thanks. Just wanted to be sure I wasn't missing something before I started scripting a persistent solution.

**Comment by maximbaz** [comment]
In case someone is looking to do the same, here's a starting point:

```
playerctl status --format '{{ playerName }}' --follow > /tmp/player-last 

playerctl -p $(tail -1 /tmp/player-last) play-pause
```

**Comment by acrisci** [comment]
Closing in favor of #161.

**Comment by KebabLord** [comment]
@acrisci i'm running the same issue on api with python. Is it possible to update to recent player trough existing signals? Something like `Playerctl.MAGIC.connect("MAGIC_SIGNAL",updatePlayer)` to see if a player exists and update the player if not with `def update(): player=Playerctl.Player()`

**Comment by acrisci** [comment]
You can start a new issue for this or come to the chat in the readme. I don't mind support issues.

Look at the PlayerManager example [here](https://github.com/altdesktop/playerctl/blob/master/examples/player-manager.py) because that's probably what you're looking for.
