### ISSUE TITLE
shuffle and loop commands don't work for Spotify

### ISSUE THREAD

**Issue by dyc3** [altdesktop/playerctl#136]
The `shuffle` and `loop` commands don't currently work with Spotify. Both commands fail to get the actual state, and to set the state.

**Comment by acrisci** [comment]
Yeah I can reproduce this with:

```
dbus-send --session --print-reply --type=method_call \
    --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.GetAll \
    string:'org.mpris.MediaPlayer2.Player'
```
And:

```
dbus-send --session --print-reply --type=method_call \
    --dest=org.mpris.MediaPlayer2.spotify \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.Set \
    string:'org.mpris.MediaPlayer2.Player' string:'Shuffle' variant:boolean:true
```

And it doesn't work.

I can't investigate further because I don't have access to the Spotify source. Contact Spotify customer support.

**Comment by sagotsky** [comment]
This bug is still happening :-\

**Comment by acrisci** [comment]
See [here](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md) for an example letter to spotify customer support.
