### ISSUE TITLE
playerctl does not work in parallel

### ISSUE THREAD

**Issue by MichaelAquilina** [altdesktop/playerctl#139]
I'm using playerctl to populate my status bar and am using the status of playerctl to determine whether to show certain buttons or not. However I've noticed that sometimes the behaviour does not work as expected and the button dissapear despite a song being played.

When investigating the issue I noticed that this seems to be playerctl not able to handle parallel requests due to some possible race condition.

Some examples:

```
$ playerctl -F metadata -f '[{{status}}]' & playerctl -F metadata -f '[{{album}}]' &
[14] 22902
[15] 22903
[Blood Club (Deluxe Edition)]                                                                                                                
$ playerctl -F metadata -f '[{{status}}]' & playerctl -F metadata -f '[{{album}}]' &
[16] 22974
[17] 22975
[Paused]                                                                                                                                     
$ playerctl -F metadata -f '[{{status}}]' & playerctl -F metadata -f '[{{album}}]' &
[18] 23050
[19] 23051
[Paused]                                                                                                                                     
$ playerctl -F metadata -f '[{{status}}]' & playerctl -F metadata -f '[{{album}}]' &
[20] 23120
[21] 23121
[Paused]                                                                                                                                     
[Blood Club (Deluxe Edition)]
```

**Comment by acrisci** [comment]
What player?

**Comment by MichaelAquilina** [comment]
Sorry should have mentioned, its Spotify

**Comment by acrisci** [comment]
Oh ok I can't reproduce this on VLC.

**Comment by MichaelAquilina** [comment]
Can't seem to reproduce this in Rhythmbox either actually.

**Comment by MichaelAquilina** [comment]
Just in case it makes a difference, this is Spotify running in Flatpak

**Comment by acrisci** [comment]
I think `--follow` is probably better for your use case instead of multiple processes in parallel. I can't fix spotify issues like this.

For an example letter to spotify customer support, see [here](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md).
