### ISSUE TITLE
Feature Request: set order of players

### ISSUE THREAD

**Issue by cphyc** [altdesktop/playerctl#143]
Hi,
Thank you very much for the amazing tool!

It would be great to have an option on the cli to set the order in which players should be considered. One way to do so would be to add a flag when listing the players. For example
```
playerctl -p spotify,ANY next
```
would trigger the `next` action on spotify (if found). Otherwise, it tries with any other player.
Internally, I guess this could be done by sorting and then push the selected players to the top of the list in the order they appear in the CLI.

**Comment by acrisci** [comment]
We could generalize and implement a wildcard character. The obvious choice is `*`, but since that's a shell character, maybe sql style with `%`.

```
playerctl -p spotify,% next
# select a player that begins with "s"
playerctl -p s% next
```

**Comment by cphyc** [comment]
That would do the trick. As for `*`, it is also possible to pass it if it is escaped, something like
```
playerctl -p 'spotify,*'
```

**Comment by crobe87** [comment]
I agree on this issue. Chrome is a PITA these days, as there's a video in nearly every web pages... after a recent update the browser is always in front of my media players. I would like to give priority back to my media players.

**Comment by Gleek** [comment]
For somebody stumbling here I have a small script that does it for me.

- Create a file defining priority (`$HOME/.player-priority`) with the following example content:
```
spotify
vlc
DeaDBeeF
mpv
mpd
```
The higher players in the list have higher priority. Any players not in the list will have a lower priority than every player in the file.
Get the names from `playerctl -l`

- Create a file `pplayerctl` in you PATH such as `/usr/local/bin` with the following contents
```bash
#!/usr/bin/env bash
playerctl --player=$((cat ~/.player-priority 2>/dev/null; echo; playerctl -l)|awk '!x[$0]++'|paste -sd,) $*
```
- Use `pplayerctl play-pause` to play-pause the player with highest priority. You can change the priority anytime by re-ordering the contents of your `$HOME/.player-priority` file

Anyways, this wouldn't be required once the feature is implemented as suggested in the comments above.

**Comment by acrisci** [comment]
If you're interested in better player selection, please join the discussion at #161.
