### ISSUE TITLE
duration function not working

### ISSUE THREAD

**Issue by muHashh** [altdesktop/playerctl#144]
The player I am using is Spotify.
I am not able to get the current position nor, the length of the track. Using, ``` {{ duration(position) }} ``` and ``` {{ duration(mpris:length) }}``` respectively; as arguments in ```playerctl metadata -f```. I am using arch and, used yay to build playerctl from the AUR.

**Comment by acrisci** [comment]
I don't think spotify supports this. I can't fix this issues in playerctl. Please contact spotify customer support.
