### ISSUE TITLE
Cannot print "playerName" "status": "playing"

### ISSUE THREAD

**Issue by Lockna** [altdesktop/playerctl#147]
The player I am using is chromium and Spotify.
I'm trying to put my {{playerName}} {{status}}: {{title}} in the top of the Polybar. I have my music module in the center.
`[module/music]
type = custom/script
interval = 1
exec = playerctl metadata --format "{{playerName}} {{ status}}: {{title}}"
label-underline = ${colors.primary}
label-background = ${colors.background-alt}
label-padding = 5
click-left = i3  workspace 10 - ` 
This is my music module.

**Comment by acrisci** [comment]
What's the error you are getting or what is the result?

**Comment by Lockna** [comment]
In the polybar there is nothing.

**Comment by acrisci** [comment]
What if you just type it on the command line?

**Comment by Lockna** [comment]
There it works

**Comment by acrisci** [comment]
Try capturing stderr and see if there is an error message. `playerctl metadata 2>&1`.

**Comment by Lockna** [comment]
`[I] lockna@lockna-pc ~> playerctl metadata 2>&1

(playerctl:15665): GLib-GIO-WARNING **: 18:26:49.444: Received property Position with type i does not match expected type x in the expected interface
chromium xesam:album
chromium xesam:artist              Guy, Robot
chromium xesam:title               How to Install i3 on Arch Linux
` This is my output

**Comment by Lockna** [comment]
Hmm, after a complete restart of the pc. Now it shows "No players found" When I start spotify it works. But I started chromium and started a video and the message has disappeared. If I start spotify again It works, But only for spotify. How can I do that if Spotify is closed and a YouTube-Video is playing?
