### ISSUE TITLE
Time remaining function

### ISSUE THREAD

**Issue by vredesbyyrd** [altdesktop/playerctl#149]
Hi, 

imho, having a function in the playerctl-cli to query a tracks _remaining time_ would be a nice addition. Something like `playerctl metadata --format "{{ duration(remaining-time) }}"   --follow` to view a countdown to 0:00. 

I have used the library do get a counter of the remaining time, with varying degrees of success. But having a quick and easy solution with the cli could be handy. Lots of my collection includes long classical pieces, and imo just displaying `remaining-time` rather than `position / length` is a good way to free up needed space in a status bar.

**Comment by acrisci** [comment]
Yeah this could be done.

**Comment by vredesbyyrd** [comment]
Right on :)

I do not know if there is a standard nomenclature for this, but just glancing at mpv's library they use `time-remaining`.

**Comment by vredesbyyrd** [comment]
Thanks for implementing this :+1:
