### ISSUE TITLE
Player Position and Volume Not working

### ISSUE THREAD

**Issue by goldcoders** [altdesktop/playerctl#156]
The player I am using is `Spotify version 1.1.10.546.ge08ef575, Copyright (c) 2019, Spotify Ltd`

i tried to use playerctl volume 0.1 + or - but volume stil the same

also when i try to fast forward or backward a song

playerctl position 10 + or - but the track wont fast forward or go backward 10 secs

im using ubuntu 19.04

my linux kernel is  5.3.0-7625-generic 

Any Help thanks

**Comment by acrisci** [comment]
I don't think Spotify implements these commands. Talk to customer support and ask them to implement all of the mpris dbus specification.

**Comment by acrisci** [comment]
I've written a [letter template](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md) to spotify customer support you can use to help you contact them.

**Comment by TornaxO7** [comment]
@acrisci What's the current situation? Did they answer to your question?

**Comment by flxai** [comment]
@TornaxO7 I understand this template to be sent by others. You may contribute sending it.
