### ISSUE TITLE
Property access unexpectedly yields control

### ISSUE THREAD

**Issue by justin-gerhardt** [altdesktop/playerctl#157]
When using the scripting API accessing properties causes control to be unexpectedly yielded back to the main loop.
To demonstrate consider
```
from gi.repository import GLib, Playerctl
import threading
import time

player = Playerctl.Player()
lock = threading.Lock()
def handler(player, event):
    with lock:
        time.sleep(1) # wait a bit for more events to arrive
        metadata = player.props.metadata

player.connect('playback-status', handler)
player.connect('metadata', handler)
main = GLib.MainLoop()
main.run()
```

This example immediately deadlocks when I start to play a song.
The first event enters the handler, takes the lock and waits a bit (giving time for the next event to arrive). Then it tries to retrieve the metadata. At this point control is given back to the main loop and the next event starts executing the handler. The second event cant take the lock and since control flow isn't yielded back to first event deadlock occurs.

I'm not familiar enough with project internals to know if this is intentional, if so it definitely should be documented somewhere.

**Comment by acrisci** [comment]
I don't think the GLib main loop is compatible with python threading. It works if you put your python threaded code in a python thread:

```python3
def threaded_func():
    with lock:
        time.sleep(1)
        metadata = player.props.metadata
        print(metadata['xesam:title'])

def handler(player, event):
    threading.Thread(target=threaded_func).start()
```

Although if you want to interact with the player from the python thread, it might be required to execute some commands back in the main loop with `[g_idle_add()](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#g-idle-add)` to avoid deadlocks.

More info:

* https://wiki.gnome.org/Projects/PyGObject/Threading
* https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html

> so it definitely should be documented somewhere.

Yeah I definitely agree. I would appreciate some help with this.

If you run into more issues, feel free to keep the discussion going here.

**Comment by acrisci** [comment]
If you want to use native python, I would suggest [python-dbus-next](https://github.com/altdesktop/python-dbus-next) which I am also the author of.
