### ISSUE TITLE
commands are applied to first but not to currently playing player

### ISSUE THREAD

**Issue by panzi** [altdesktop/playerctl#159]
I use Audacious and Amarok. I had music playing in Audacious and triggered `playerctl play-pause` (and another time `playerctl next`) and instead of issuing that command to Audacious to pause it, it made Amarok continue playing and thus two things played at once. And for the `next` case it made Amarok go to the next track and play it instead of doing that for the currently playing Audacious.

**Comment by panzi** [comment]
Pull request to fix this: https://github.com/altdesktop/playerctl/pull/160

**Comment by acrisci** [comment]
I don't want to integrate this feature into Playerctl because of the reasons I outlined in the PR.

But I would be happy to consider adding it to the proposed `playerctld` in #161.

**Comment by acrisci** [comment]
playerctld is now ready to be tested, merged in #164.
