### ISSUE TITLE
Coredump when using --format

### ISSUE THREAD

**Issue by edi9999** [altdesktop/playerctl#162]
The player I am using is vlc. playerctl 2.0.2

When I run : 

```
playerctl metadata --format 'position: {{ minutes(mpris:length) }}:{{ seconds(mpris:length) }}'
```

I get : 

```
Could not execute command: unknown template function: minutes
free(): invalid pointer
Aborted (core dumped)
```

I know this command may be incorrect, but having a core dumped still seems like a bug, the command should fail without unexpected core dumps.

**Comment by acrisci** [comment]
I think this is fixed in master.
