### ISSUE TITLE
Playerctl next and previous doesn't work with youtube

### ISSUE THREAD

**Issue by sebPomme** [altdesktop/playerctl#165]
HI,

The player I am using is youtube (via chrome `Google Chrome Version 79.0.3945.130 (Build officiel) (64 bits)` and chromium `Opera 66.0.3515.36`).
```
% playerctl --list-all   
chrome.instance1917
chromium.instance32268
```
My playerctl version:
```
% playerctl --version 
v2.0.2
```
So since two weeks `playerctl next` and `playerctl previous` doesn't work anymore.
Trying compile playerctl by source gives the same result: nothing happend when I run `playerctl next`.
The `play-pause` and `stop` keeps working.

**Comment by sebPomme** [comment]
Hi, 
Just a short update.  
I think this linked to youtube.com.  

Cause I tried it with other player: music.youtube.com, soundcloud.com (tested on `Google Chrome Version 80.0.3987.163 (Build officiel) (64 bits)` and `Opera Version :67.0.3575.115` ). 
`playerctl next` & `playerctl previous` works like charms with theese.

For me, the issue can be closed.

Thanks for this nice projet :smiley:

**Comment by twiclo** [comment]
So what did you do to fix youtube not working here?

**Comment by sebPomme** [comment]
> So what did you do to fix youtube not working here?

Nothing, now it's works with youtube only when a playlist is playing

**Comment by twiclo** [comment]
I'm currently in a playlist where play/pause works but skip doesn't. The player shows up in `playerctl -l`. Maybe we should re-open this?

**Comment by fockboi-lgtm** [comment]
I think's dependent on the type of video. It seems I can't use `next or prev` on a normal video. It would work only a music video. 
@sebPomme can you confirm, was facing a same issue.

**Comment by sebPomme** [comment]
@fockboi-lgtm Exact.
According to the situation (single video playing | playlist) or the video type, `next or prev` kinda works.

@twiclo Maybe try to update you web browser

**Comment by fockboi-lgtm** [comment]
Yeah I think it's probably only happening with playlists, not the autoplay that YouTube has.

**Comment by acrisci** [comment]
If you really want this fixed, someone needs to go take care of the mpris implementation on Chromium.

**Comment by fockboi-lgtm** [comment]
Probably, they won't fix. Will have an ad instead telling the users to use Youtube Premium.

**Comment by myryk31415** [comment]
Probably also an issue on youtube's end: playerctl position doesn't work either
