### ISSUE TITLE
emoji() function broken on 2.1.1

### ISSUE THREAD

**Issue by ad1217** [altdesktop/playerctl#167]
The player I am using is https://github.com/f1u77y/wmc-mpris.
I'm using the Arch Linux package for playerctl.

When running `metadata --format '{{ emoji(status) }}'` (also volume), which worked on 2.0.2, I now get:

```
(playerctl:284364): playerctl-WARNING **: 10:45:41.811: got unknown loop status:
Could not execute command: the emoji function can only be called with a variable
```

**Comment by acrisci** [comment]
Oh yeah that's broken.
