### ISSUE TITLE
Multiple mpv instances lead to multiple signal issuing

### ISSUE THREAD

**Issue by Zocker1999NET** [altdesktop/playerctl#169]
The player I am using is mpv (with [mpv-mpris](https://github.com/hoyon/mpv-mpris)). I discovered this issue using my own script, but I can confirm this issue using this [example](https://github.com/altdesktop/playerctl/blob/master/examples/player-manager.py) for the Playerctl Python bindings.

The bug is that Playerctl seems to receive / trigger signals for players which have vanished before. To find this bug, do the following:

0. Optional: In the example script, change the appearances of `player.props.player_name` to `player.props.player_instance` for better differing the multiple instances of mpv running. Without the change, the bug will also occur but seems even more weird.
1. Start the script and let it running in the background
2. Launch a first instance of mpv (after some seconds playing you can pause it)
3. Launch a second instance of mpv (same as above)
4. Kill the **first** instance, it does not work if you kill the *second* instance
5. Resume playing on the second instance (issuing the example script to log this), this can be repeated several times

The expected log (with comments referring to the steps above) of the example script should be (with the modification, pid can differ):
```sh
# Launch first instance
player is playing: mpv
# Launch second instance
player is playing: mpv.instance804148
# Exit first instance
player has exited: mpv
# Resume second instance
player is playing: mpv.instance804148
```

But for me it is actually (with the modification, pid can differ):
```sh
# Launch first instance
player is playing: mpv
# Launch second instance
player is playing: mpv.instance804148
# Exit first instance
player has exited: mpv
# Resume second instance
player is playing: mpv
player is playing: mpv.instance804148
```

(without the modification, `mpv.instance804148` would also be `mpv`, which can be confusing)

Playerctl seems to have problems with mpv first naming its instance `mpv` and `mpv.instancePID` the second time. But the issue does not apply if both instances run simultaneously. The developer of mpv-mpris [states](https://github.com/hoyon/mpv-mpris/issues/7#issuecomment-323761867) this behaviour is following the [MPRIS specification](https://specifications.freedesktop.org/mpris-spec/latest/#Entry-point). Even playerctl instances launched after exiting the first mpv instance (but while the second one is still present) list multiple mpv instances even if only a single process is still opened:
```
$ playerctl --list-all
mpv.instance804148
mpv
```
As I do not know much about d-bus interfaces, I hope you can take a look on this issue and maybe fix it, if Playerctl does mess up with something. Thank you for your work on Playerctl.

**Comment by acrisci** [comment]
I can confirm this and I believe it is a bug in playerctl causing this issue.

**Comment by acrisci** [comment]
I looked into it further and found a bug in mpv-mpris that I believe is causing this behavior.

Confirm this works here:

https://github.com/hoyon/mpv-mpris/pull/35
