### ISSUE TITLE
Spotify metadata when listening on another device with Spotify Connect

### ISSUE THREAD

**Issue by thdb-theo** [altdesktop/playerctl#177]
When I have Spotify open on my computer, but I play on my phone through Spotify Connect, playerctl recognise it as a player, but the only metadata it gets is what album is currently playing.

Example:
`playerctl metadata --player=spotify`
```spotify mpris:trackid             spotify:track:19YKaevk2bce4odJkP5L22
spotify mpris:length              314075000
spotify mpris:artUrl              https://open.spotify.com/image/ab67616d00001e02c5649add07ed3720be9d5526
spotify xesam:album               Blonde
spotify xesam:albumArtist         
spotify xesam:artist              
spotify xesam:autoRating          0.0
spotify xesam:discNumber          0
spotify xesam:title               
spotify xesam:trackNumber         0
spotify xesam:url                 https://open.spotify.com/track/19YKaevk2bce4odJkP5L22
```

**Comment by acrisci** [comment]
Spotify supports most of mpris, but not these features. I've written a [letter template](https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md) you can use to contact spotify customer support.
