### ISSUE TITLE
Output cannot be piped

### ISSUE THREAD

**Issue by ONDRA5** [altdesktop/playerctl#178]
I'm using playerctl to populate my dwmbar:
```
playerctl metadata --format " {{ title }} "
```
But sometimes titles are really long, for example with YouTube videos, so I wanted to shorten the output by:
```
playerctl metadata --format " {{ title }} " | cut -c 1-15
```
Only to find out that no output from playerctl can be piped. 
(It doesn't matter if I add echo to the script or not).

**Comment by acrisci** [comment]
It works for me in the terminal. It might be a problem with your bar script. If you want to post more info I'll see if there's anything wrong with it.

**Comment by ONDRA5** [comment]
I checked the script and it worked when there was something playing.
But when the playerctl errored out (I think that spotifyd is here to blame) and didn't see any player, the error couldn't be piped.
My script:
```
#!/bin/sh
song="$(playerctl metadata --format " ▶ {{ title }}" | cut -c 1-15)"
echo -e "$song... "
```
So for example when a music is playing, I get this output:
```
 ▶ Silence in...
```
But when there's an error, or no player available, I get the full error text:
```
No player could handle this command
```

**Comment by acrisci** [comment]
Error messages are printed to stderr which the bar is ignoring. You can combine stdout and stderr with `2>1`. Check for errors and only cut if the command succeeded. This is how I would do it.

```bash
#!/bin/env bash

song=$(playerctl metadata --format " ▶ {{ title }} 2>1")

if [[ $? = 0 ]]; then
    echo ${song} | cut -c 1-15
else
    echo -n ${song}
fi
```

**Comment by ONDRA5** [comment]
Thanks, this helps.
I wrote more sane alternative to cut using sed, so that titles that don't exceed set number of characters don't have those dots displayed at the end.
Now I just have to figure out how to differentiate between error state and when there actually aren't any players available.

**Comment by acrisci** [comment]
stdout will be empty.

```bash
if [[ -z $(playerctl -l) ]];
    # handle no players found
fi
```
