### ISSUE TITLE
Hangs on firefox nightly build '78.0a1 (2020-06-01) (64-bit)'.

### ISSUE THREAD

**Issue by Liupold** [altdesktop/playerctl#179]
The player I am using is Firefox.
Firefox stops immediately but the command hangs. Using a workaround for now.

```timeout 0.5 playerctl pause```

**Comment by Liupold** [comment]
same happens on '77.0.1 (64-bit)' (stable). , player pauses media but the command hangs.

**Comment by ya-isakov** [comment]
It's a known issue in Firefox - https://bugzilla.mozilla.org/show_bug.cgi?id=1648874.

**Comment by acrisci** [comment]
It's fine on firefox 79. The issue says they resolved it so it's being maintained there.

**Comment by ya-isakov** [comment]
I've checked firefox 79, and the problem is still here. And comment in the issue was mine, that I've managed to fix it by adding missed line in my build of Firefox, not in upstream code. Anyway, the bug is in Firefox itself, so for Playerctl nothing could be done, I think.

**Comment by ya-isakov** [comment]
In Firefox 83, no problem anymore (probably was fixed in version some before)
