### ISSUE TITLE
No players were found

### ISSUE THREAD

**Issue by erzoe** [altdesktop/playerctl#183]
The player I am using is quodlibet.

Quodlibet is open but

    $ playerctl play
    No players found

I have followed the advice in the [readme](https://github.com/altdesktop/playerctl#no-players-found).
I have installed `dbus-launch` with

    # apt install dbus-x11

created `~/.xinitrc` with the content

    exec dbus-launch --autolaunch=$(cat /var/lib/dbus/machine-id) i3

and rebooted the computer.
But it made no difference, playerctl does still not find any players.

I have removed the xinitrc file again and uninstalled dbus-x11 and the environment variable `DBUS_SESSION_BUS_ADDRESS` is still set, so I am assuming it was there all along.

Tested with the following versions:
- Quod Libet 4.2.1
- playerctl v2.0.1
- D-Bus Message Bus Launcher 1.12.20

-----

Also I have noticed that `man dbus-launch` says regarding `--autolaunch`:

> This option is for the exclusive use of libdbus, you do not want to use it manually. It may change in the future.

**Comment by acrisci** [comment]
You have to install a plugin. `File -> Plugins` and install "MPRIS D-Bus Support".

**Comment by erzoe** [comment]
Yes, thank you. That has solved it. I'll create a merge request which adds this to the readme.
