### ISSUE TITLE
No player detected while using Firefox (fixed)

### ISSUE THREAD

**Issue by FjorgeTheHuman** [altdesktop/playerctl#184]
The player I am using is whatever Firefox uses.

When typing in 'playerctl play-pause', it says that no players were found.

EDIT: Got plasma browser integration and it worked

**Comment by FjorgeTheHuman** [comment]
I forgot to mention that it was working perfectly fine in the Opera browser. I switched to Firefox recently.

**Comment by acrisci** [comment]
:+1:
