### ISSUE TITLE
Firefox on Ubuntu 20.04 with i3

### ISSUE THREAD

**Issue by abitrolly** [altdesktop/playerctl#186]
The player I am using is SoundCloud running in Firefox 79.

And `playerctl` doesn't detect it.

**Comment by acrisci** [comment]
Some people can get firefox to work with [plasma browser integration](https://community.kde.org/Plasma/Browser_Integration).

**Comment by abitrolly** [comment]
It requires plasma desktop to be installed and my machine uses `i3`.

**Comment by acrisci** [comment]
I don't see plasma desktop in the [dependencies](https://packages.ubuntu.com/focal/plasma-browser-integration) but it does have some sort of heavy qt and kde libraries. I've used it before with i3 and it worked ok.

**Comment by abitrolly** [comment]
Tries to fetch 138Mb of dependencies together with `plasma-framework`. I would prefer something more lightweight and security tested by Mozilla https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/

![image](https://user-images.githubusercontent.com/8781107/91314021-c0a40a80-e7be-11ea-8657-f9e5de5eab64.png)

**Comment by acrisci** [comment]
I've submitted a patch to firefox at https://bugzilla.mozilla.org/show_bug.cgi?id=1648874

If you want this issue to be resolved, please support that issue.

**Comment by abitrolly** [comment]
@acrisci thanks. Voted for it.
