### ISSUE TITLE
(playerctl:21639): GLib-GIO-WARNING **: 12:56:25.316: Received property Position with type i does not match expected type x in the expected interface Stopped

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [altdesktop/playerctl#190]
The player I am using is spotify.
![image](https://user-images.githubusercontent.com/33642056/92332070-98c76900-f040-11ea-85d3-0b62927c53b3.png)
 
it pauses and plays the song but when i run playerctl status it returns that, it was working earlier in the day but after rebooting it stopped

**Comment by nerdthatnoonelikes** [comment]
ok so i was a little vague on my issue, the issue is that when i check playerctl status it says stopped even though spotify is playing music

**Comment by acrisci** [comment]
This is a spec violation on the part of Spotify. You should contact customer support to ask them to improve their mpris implementation.

There might be something I can do on my side to fix this by accepting an invalid type for the position that I will look into.

**Comment by nerdthatnoonelikes** [comment]
alright thanks
