### ISSUE TITLE
(Solved) X&Y album 

### ISSUE THREAD

**Issue by peter-kl** [altdesktop/playerctl#196]
hello,

Funny thing when the metadata name album is **X&Y** the `playerctl metadata --format " {{ album }} "`
doesn't  appear but after I change it to **x and y** voilá is working. And  I tried using _lc_ and _uc_

`mpv   mpris:trackid             '/0'

mpv   xesam:contentCreated      2005-01-01T00:00:00Z

mpv   xesam:albumArtist         Coldplay

**mpv   xesam:album               x and y**

mpv   xesam:genre               Rock

mpv   mpris:length              329698667

mpv   xesam:artist              Coldplay

mpv   xesam:title               White Shadows
`

I`m talking about running the command in a script to tint2. Very basic bash thing as I echo the command as a variable. 
Works perfect with several players I tested and a bunch of mp3 musics, the "problem" is the _**&**_  even if I change it to jon & joan does not work but jon and joan works same with x and y. 

==> Solved:
Was in tint2 executor `execp_markup = 0`

**Comment by acrisci** [comment]
I can't reproduce this.

```
~> playerctl -p mpv metadata --format '{{album}}'
An & Album
~> playerctl -p mpv metadata --format '{{lc(album)}}'
an & album
```

The problem might have to do with how your bar escapes the `&`. Try using `playerctl -p mpv metadata --format '{{lc(markup_escape(album))}}'`.

**Comment by peter-kl** [comment]
Hi, thanks,

Works great in a teminal and in a simple bash  script: 
`aa=$(playerctl metadata --format "<b>{{ lc(artist) }}</b> ▫️{{ album }}"`
and them with `echo "♫ $aa ` in a if statement also works except  that **&** 
[imgur-x and y](https://imgur.com/hUysmNA)
[imgur-x&y](https://imgur.com/1FeH9BX)
Test your options same result. An  hiccup the rest is great!!

**Comment by acrisci** [comment]
`$(playerctl metadata --format "<b>{{ lc(markup_escape(artist)) }}</b> ▫️{{ markup_escape(album) }}"`

**Comment by peter-kl** [comment]
Now none of the others mp3 works with above command.
I have several options without album, with time duration, title, artist etc so I just choose one of them, is just this particular case all other albums are working.

**Comment by acrisci** [comment]
Since your bar is parsing markup, you should always use the `markup_escape()` function every time you print a variable. Playerctl seems to be working fine.

**Comment by peter-kl** [comment]
Hello,
I just edit  Tint2 executor: 
`execp_markup = 0`

**playerctl** works great!!

**Comment by acrisci** [comment]
:+1:
