### ISSUE TITLE
Request: wildcard support in player names

### ISSUE THREAD

**Issue by AndydeCleyre** [altdesktop/playerctl#203]
The player I am using is spotpris2, among others.

Some classes of players that I'd like to predictably control can use variable names that match a pattern, such as chromium items, or in the case of spotpris2, things like `spotpris.device5e4e5ba5cb57374aab4c67bd28fdf872388edd53`.

I'd like to be able to run a command like

```console
$ playerctl -p 'spotify,ncspot,mopidy,spotifyd,spotpris.device*' play-pause
```

I don't wish to use the `%any` name, because there are players I never wish to control with this tool.

**Comment by acrisci** [comment]
As of d0a59e2 (dev version), the name `spotpris` will match all `spotpris.device*` like you would expect.

> there are players I never wish to control with this tool

This is what `--ignore-player` is for.

**Comment by AndydeCleyre** [comment]
Excellent, thank you. Will it similarly work with `spotpris.device`?

The `--ignore-player` option isn't for me, because I can't anticipate all the potential surprise players I want to ignore, only the ones I do want to control with this tool.

**Comment by acrisci** [comment]
The exact rule is a player name like `spotpris` will match a player named `spotpris` and any `spotpris.*`.

Try it out and see if it works for you. I have a snap package you can get the dev version with `snap install --edge playerctl`.
