### ISSUE TITLE
ubuntu package version bump

### ISSUE THREAD

**Issue by SpanishPear** [altdesktop/playerctl#205]
https://launchpad.net/ubuntu/+source/playerctl currently lists the most recent version as `2.0.2` - wheras the latest release is [2.2.1](https://github.com/altdesktop/playerctl/releases/tag/v2.2.1)

Possible to get a version bump on the ubuntu package? 

Building 2.2.1 from source doesn't work for me (using player spotify or spotifyd) , results in the following: 
```
$ playerctl --player=spotify status                                                                                                 
playerctl: symbol lookup error: playerctl: undefined symbol: pctl_player_has_cached_property

$ playerctl -status                                                                                                             
playerctl: symbol lookup error: playerctl: undefined symbol: pctl_player_has_cached_property

$ playerctl status                        
playerctl: symbol lookup error: playerctl: undefined symbol: pctl_player_has_cached_property
```

Similarly, installing the binary directly results in: 
```
$ playerctl status
playerctl: symbol lookup error: playerctl: undefined symbol: pctl_player_get_instance
$ playerctl pause
playerctl: symbol lookup error: playerctl: undefined symbol: pctl_player_get_instance
$ playerctl -l
spotifyd
spotify
```

both give `2.2.1` when running playerctl -v

**Comment by SpanishPear** [comment]
Worth noting that as per #191 - I also tried installing on snap, but run into 
```
$ playerctl --all-players status
Could not connect to players: Could not connect: Permission denied
```

which, when run with sudo - resulted in: 
```
$ sudo playerctl --all-players status
Could not connect to players: Failed to execute child process ?dbus-launch? (No such file or directory)

```

**Comment by acrisci** [comment]
Installing from source will work correctly if you do it right, but it's hard for me to support. It's probably finding the system libraries instead of the ones you built somehow.

As for the version Debian takes, that's up to my packagers. I'm going to make another release in probably a month so it's probably best to wait until then to notify them.

As for the snap, I just released it a few days ago. Those look like permission issues that are pretty easy to resolve. I should get around to that soon.

**Comment by SpanishPear** [comment]
No rush on my end (symlink did the job) , just posting so you're aware, and that anyone else who comes across issues can get it working in the meantime :)

**Comment by knowledgejunkie** [comment]
I uploaded playerctl 2.3.1 to Debian on Feb 7. Having just checked, I see that 2.3.1 is in the proposed updates queue for Ubuntu 21.04 "Hirsute Hippo", due for release late Apr.

Hope this helps!
