### ISSUE TITLE
Default player to MRU, possibly a regression?

### ISSUE THREAD

**Issue by OJFord** [altdesktop/playerctl#209]
The player I am using is Firefox & Spotify.

I relatively recently started using `playerctl`, and with FF & Spotify, the two players I tend to have open, it was working great and seemed to generally pause whichever was currently playing, and I think play whichever had most recently played, or possibly whichever had most recently been the active window.

Now however, it seems to always target Firefox. For example, I'm currently listening to Spotify, and if I press my key bound to `play-pause`, instead of Spotify pausing, a Youtube playlist I was watching earlier starts playing as well.

I'm using v2.3.1. This is a bit of a hand-wavy issue because I'm not sure what the behaviour is actually supposed to be if `--player` is not specified? Perhaps it's not actually a regression, the order:
```
$playerctl -l
firefox.instance1573
spotify
```

is defined by dbus, and without `-p` the first is taken; that used to 'do the right thing' (as it seemed to me) because of dbus behaviour rather than playerctl?

**Comment by OJFord** [comment]
I did not intend for the bug label to be added - I don't know that this is a bug.

**Comment by acrisci** [comment]
There has been a change in how the players are ordered when no player is specified. The order without specifying the player has never been defined specifically, so I don't consider this to be a bug or a breaking change. The multi-player use case has never been well supported without some configuration. See the section in the readme about player selection for your options. I also recommend using playerctld which will give you the behavior you expect in the issue by running `playerctld daemon` after your session starts.

**Comment by OJFord** [comment]
Splendid, many thanks.

In case it's of any use to anyone else, I added a systemd user unit:
```ini
[Unit]
Description=playerctl daemon to find appropriate player to control
Before=mpris-proxy.service

[Service]
ExecStart=/usr/bin/playerctld

[Install]
RequiredBy=mpris-proxy.service
WantedBy=default.target
```

(I think `mpris-proxy.service` I took from the Arch wiki, it just runs `mpris-proxy` to forward the control from my Bluetooth headset. I didn't mention this in OP but a - related, it turns out - issue was that that stopped working completely, i.e. not even play/pausing Firefox. If you don't use that you can just omit those lines above.)

**Comment by acrisci** [comment]
I considered including a unit file, but playerctld can run once per graphical session, and there may be zero to many graphical sessions per systemd user session.

**Comment by OJFord** [comment]
Yep no problem, this works for me and my use, I only commented since someone else may stumble on the issue and find it useful (it's been me) - not to say that you should include it in the release. :slightly_smiling_face:
