### ISSUE TITLE
playerctl works but keys don't

### ISSUE THREAD

**Issue by J-Cake** [altdesktop/playerctl#214]
Hi everyone, I've just discovered this and love it. It's powerful and fast, but I have a slight problem - I'd like to be able to control the players through the media keys. It works through browsers and the spotify client etc, but my current setup as demonstrated below is only controllable through `playerctl` on the command line.

My setup is this: 
OS: KUbuntu 20.04
I have [Spotifyd](https://github.com/Spotifyd/spotifyd) installed with the `dbus_mpris` flag enabled, thus I can control the player through the command line, however, I cannot use the media keys to control the player. I'm wondering if this is a bug or whether I haven't configured my system correctly. 

Thanks for any pointers

**Comment by acrisci** [comment]
This project won't automatically do that. There are settings in KDE to bind keyboard keys to command line commands. I'm not sure how to do that because I don't use KDE.

**Comment by J-Cake** [comment]
Ah not a problem. I was just hoping that there was some underlying API that X calls automatically when the media keys are pressed or something remotely similar. I was hoping to avoid the command-line though
