### ISSUE TITLE
Getting permission denied error when installing on Ubuntu 20.04 using snap

### ISSUE THREAD

**Issue by danwoodbury** [altdesktop/playerctl#216]
When installing via the snap I keep getting a permission denied error.

```
$ playerctl --player=spotify status
Could not connect to players: Could not connect: Permission denied
```
```
$ playerctl -l                     
Could not connect: Permission denied
```

Similarly, when running with sudo I am getting:
```
Failed to execute child process ?dbus-launch? (No such file or directory)
```

*Edit:*

I just installed using the .deb package on version 2.0.1 and it seems to be working fine

**Comment by acrisci** [comment]
I'm working with the snap people to make it work now.

**Comment by ChildishGiant** [comment]
Same issue, I think this is because of snap sandboxing

**Comment by acrisci** [comment]
I gave up on the snap. I'm going to set it to private.
