### ISSUE TITLE
Attempting to get a "global player state" display

### ISSUE THREAD

**Issue by fuadsaud** [altdesktop/playerctl#217]
What I'm trying to achieve:

A script that echoes player status/metadata for a [polybar](http://github.com/polybar/polybar) module (but could potentially work for any other bar) which displays formatted metadata and control buttons.

Right now I have this prototype:

```
function status_to_icon {
  while read -r status; do
    if [ "$status" = "Stopped" ]; then
      echo :arrow_forward: 
    elif [ "$status" = "Paused"  ]; then
      echo :arrow_forward:
    else
      echo :pause_button:
    fi
  done
}

playerctl status --follow 2>/dev/null | status_to_icon
```

This mostly works, but there's an unexpected behavior:

**Steps to reproduce**

Play player A
Play player B (both players will be playing at the same time)
Pause player c

**Expected behavior**

Play/pause icon should be :pause_button: (because player A is still playing)

**Actual behavior**

Play/pause icon is :arrow_forward:

I understand this happens because `--follow` simply notifies individual player events and no event actually happened on player A after the events from player B. Is there a trivial solution to this I might not be seeing?

**Comment by fuadsaud** [comment]
btw, this assumes `playerctld` is running. I'm not sure how well `playerctld` works with `--follow`, but in my experiments apparently it mostly works.

**Comment by acrisci** [comment]
This is the use case for format strings. Try this.

```
playerctl metadata --follow --format '{{playerInstance}} : {{emoji(status)}}'
```

**Comment by fuadsaud** [comment]
@acrisci thanks for the quick response.

If I understand correctly, what you suggest is equivalent to what I'm already doing, except you're getting the emoji from `playerctl` itself (which is nice, I didn't know that was an option). However, that still poses the same problem I described.

Maybe reframing the problem in terms of the `playerctld` behavior might make more sense:

If two players A and B are playing, and player A is paused, `playerctld` will report player A as the current one, even though player B is still playing. Intuitively, I would expect `playerctld` to report B as the current player. This would mean treating players as a "stack" where they're pushed (when they start playing), popped (when they're paused, stopped) and reordered (when they're interacted with). The current implementation of `playerctld` only reorders them, which is why it behaves the way I described.

That said, to achieve the outcome I want I'd either have to have a patched version of `playerctld` running or maybe write a "wrapper daemon" that uses `playerctld` and keeps the additional state necessary.

Does that make sense?

**Comment by acrisci** [comment]
I think you want to prioritize players based on status. I'd have to think about how to do that.

**Comment by acrisci** [comment]
By the way, what you're describing is the intended behavior. Playerctld determines which player is active based on activity, not playback status. Any interactivity including seeks and track changes will make that the active player.

**Comment by acrisci** [comment]
See the feature issue.
