### ISSUE TITLE
Warning messages appear even with the `--no-messages` flag

### ISSUE THREAD

**Issue by thecountoftuscany** [altdesktop/playerctl#219]
The player I am using is `playerctld` controlling `mpd` via `mpd-mpris` (also happens with `playerctld` controlling `chromium` via `plasma-browser-integration`.

When using `playerctl -p playerctld metadata --format '{{ artist }} - {{ title }}' --follow --no-messages`, the following warning appears:
```
(playerctl:21183): playerctl-WARNING **: 13:09:23.080: Playback status not set on track change; getting status from interface instead
```

This breaks displaying the information on my status bar (`i3blocks`). Not sure if the problem with setting status could be easy to fix, but could this warning be suppressed when `no-messages` is passed?

**Comment by acrisci** [comment]
I'll change the warning logs to debug logs. Use something like `playerctl 2>/dev/null` for now.

**Comment by thecountoftuscany** [comment]
Okay, thanks.
