### ISSUE TITLE
Chromium players not detected using NixOS

### ISSUE THREAD

**Issue by JorisBlanken** [altdesktop/playerctl#220]
Linux 5.4.87
NixOS 20.09.2538.0cfd08f4881 (Nightingale)
playerctl v2.2.1

I'm using playerctl on NixOS with X11 and playerctl consistently fails to detect players in chromium based applications.
I have tried the following chromium based applications:
- Google Chrome / 87.0.4280.141
- Chromium / 87.0.4280.141
- Brave / 1.18.75 Chromium: 87.0.4280.101
- Opera / 68.0.3618.63
- Discord (electron) / 0.0.13

Any playback control command simply returns `No players found` when only chromium applications are playing.
Browsers such a firefox work fine however.

**Comment by JorisBlanken** [comment]
Issue persists on playerctl v2.3.1

**Comment by acrisci** [comment]
If playerctl can't find the player, it means it doesn't appear on the session bus. Some players require a special variable in the session to work correctly. See the [troubleshooting section](https://github.com/altdesktop/playerctl#no-players-found) for instructions on how to set that variable on startup.

**Comment by WillMeakin** [comment]
I had this issue with Chrome 108.0.5359.94.
I solved it by going to chrome://flags and setting the "Hardware Media Key Handling" flag to "Enabled.

I don't know why it became disabled.
