### ISSUE TITLE
[Feature request] Ability to query the player being controlled/monitored by playectld

### ISSUE THREAD

**Issue by thecountoftuscany** [altdesktop/playerctl#227]
Using `playerctl --player playerctld metadata --format '{{ playerName }}'` returns, as expected, `playerctld`. It would be very useful to (alternatively) define another variable that returns the name of the player being controlled / monitored by playerctld, instead of just returning `playerctld`. As an example use case, this can be used to show which player is playing (or being controlled) in a status bar.

**Comment by acrisci** [comment]
New in the latest version, the player list is taken from `playerctld` automatically if it is running. Simply `playerctl -l` will give a sorted list of players with the active one on top according to playerctld.

**Comment by thecountoftuscany** [comment]
Thanks! Probably a good idea to update the readme with this information.
