### ISSUE TITLE
No library signals when used within AwesomeWM

### ISSUE THREAD

**Issue by regan3** [altdesktop/playerctl#233]
I've asked this question over at [awesomeWM/awesome](https://github.com/awesomeWM/awesome/issues/3311) but I thought I would ask here as well. I am trying to use the playerctl library from within my AwesomeWM configuration using the lua bindings from [lgi](https://github.com/pavouk/lgi/). I am able to access the library but connecting to any of the library signals does not appear to work. Here's an example

```
local naughty = require("naughty")
local Playerctl = require("lgi").Playerctl

local manager = Playerctl.PlayerManager()

function manager:on_name_appeared(name)
    naughty.notification {
        title = "New player detected",
        message = name.name
    }
end
```
This code from my AwesomeWM config should generate a desktop notificaiton when a player is started, but I don't see anything after starting Spotify. I also ran the following code as an independent lua script outside of Awesome.

```
local lgi = require("lgi")
local GLib = lgi.GLib
local Playerctl = lgi.Playerctl

local manager = Playerctl.PlayerManager()

function manager:on_name_appeared(name)
    print(string.format("New player detected: %s", name.name))
end

local main = GLib.MainLoop()
main:run()
```

With this code I do see the expected print statement when a player is started. I am not very familiar with GLib, but I know Awesome runs its own main loop at startup via a call to `g_main_loop_run()` so I thought the playerctl signals would be able to work within that loop. I know this  may be more related to AwesomeWM code but thought you might have an idea as to why this doesn't work or if it's even possible.

**Comment by musjj** [comment]
Can you please share how you solved this?

**Comment by HumblePresent** [comment]
The [issue](https://github.com/awesomeWM/awesome/issues/3311) I linked above has more info on the solution. The problem had to do the playerctl code running before Awesome's main loop starting. If you are interested in using playerctl with AwesomeWM there is also a nice lua wrapper around this library in the [bling](https://blingcorp.github.io/bling/#/README) module.

**Comment by musjj** [comment]
Honestly didn't expect a response from a 2-year-old thread, so this was a pleasant surprise :D

I tried using `gears.timer.delayed_call`, but it didn't work. I switched to the `bling` library instead, and it's working well so far aside from a few bugs.
