### ISSUE TITLE
"No players found" when run from terminal, but works from polybar

### ISSUE THREAD

**Issue by juacq97** [altdesktop/playerctl#237]
Hi! I'm using a polybar module to show the information from spotify using playerctl and works perfect (well, it shows the name of youtube videos and music from kdeconnect too, but it's fine). Now I want to write a conky to show the name and artist of the songs, but playerctl says "No player found". I ran playerctl from the terminal and receive the same message, though I'm runing right now the spotify module. It happens with all the players (firefox and kdeconnect), the terminal says "No player found" and the polybar module shows the information just fine. Any idea why this happens? Thanks!!
![playerctl](https://user-images.githubusercontent.com/7623047/117580187-04704300-b0b4-11eb-8e8a-7a11986e87c5.png)

**Comment by acrisci** [comment]
Read the [troubleshooting](https://github.com/altdesktop/playerctl#troubleshooting) section of the readme. This is most often a problem of some environment variables not being set by the session manager.

**Comment by juacq97** [comment]
I did it without success. I'm trying plasma 5 right now lauched from sddm to check if is something related to minimal window managers and xinit (isn't the only reason though). All the plasma widgets related to music works, and kdeconnect shows the song playing in the pc, but playerctl still says "no player found". I'm using arch linux and is up to date.
