### ISSUE TITLE
[Question] Is there a way to get Spotify Podcast metadata?

### ISSUE THREAD

**Issue by uncomfyhalomacro** [altdesktop/playerctl#238]
I am currently using spotifyd. Not sure if it is spotifyd that cannot get podcast metadata or playerctl or both.

**Comment by ChevySSinSD** [comment]
I have the same issue.  I am running spotifyd and also spotify-tui as my player.  Spotify-tui is able to display all the metadata for the podcast track playing, but playerctl does not.  Playerctl does handle song metadata without issue.

**Comment by uncomfyhalomacro** [comment]
> I have the same issue. I am running spotifyd and also spotify-tui as my player. Spotify-tui is able to display all the metadata for the podcast track playing, but playerctl does not. Playerctl does handle song metadata without issue.

It is working now :) going to close
