### ISSUE TITLE
Spotify client not fully supported?

### ISSUE THREAD

**Issue by PoisonFrog** [altdesktop/playerctl#239]
I can't change position or volume in Spotify using playerctl, is it a limitation of the application or is there a way to make this work?

**Comment by acrisci** [comment]
It's a known limitation with the Spotify client. Contact their customer support to ask them to fix it.

https://github.com/altdesktop/playerctl/blob/master/letter-to-spotify-support.md

**Comment by flexiondotorg** [comment]
I noticed that Spotify has recently been updated and can now be fully controlled using `playerctl`, including changing volume, position, loop and shuffle which previously didn't work 🥳

**Comment by flipsi** [comment]
> I noticed that Spotify has recently been updated and can now be fully controlled using `playerctl`, including changing volume, position, loop and shuffle which previously didn't work partying_face

Sound great! But for me, it unfortunately still doesn't work. 
I'm using the following Spotify version:
```
> spotify --version
spotify: /usr/lib/libcurl-gnutls.so.4: no version information available (required by spotify)
Spotify version 1.1.84.716.gc5f8b819, Copyright (c) 2022, Spotify Ltd
```

**Comment by PoisonFrog** [comment]
> Sound great! But for me, it unfortunately still doesn't work. I'm using the following Spotify version:

I'm using the same version and it is working for me. Are you using valid commands?
Try these:
```
playerctl -p spotify position 60+
playerctl -p spotify position 60-
playerctl -p spotify volume 0.02+
playerctl -p spotify volume 0.02-
```

**Comment by flipsi** [comment]
> > Sound great! But for me, it unfortunately still doesn't work. I'm using the following Spotify version:
> 
> I'm using the same version and it is working for me. Are you using valid commands? Try these:
> 
> ```
> playerctl -p spotify position 60+
> playerctl -p spotify position 60-
> playerctl -p spotify volume 0.02+
> playerctl -p spotify volume 0.02-
> ```

Thank you very much (and sorry for my late reply)!

I guess the answer is *almost*: `-p spotify` did the trick! Interestingly enough, the `volume` command does not work without it, whereas the `play-pause` command does.
