### ISSUE TITLE
Make playerctld consider active player

### ISSUE THREAD

**Issue by madprops** [altdesktop/playerctl#242]
I'm on playerctl v2.3.1, thank you btw, it's pretty useful.

I think "-p playerctld" could be improved a bit. 

Here's one case:

1) Have player A and player B open
2) Play both players
3) Now pause player A because you only want player B
4) After a while you intend to pause the active player (B)
5) But the last focused player was A (when you paused it)
6) This is not what you intended

Maybe it should reject paused players when there are players already 'playing' ?

**Comment by acrisci** [comment]
I think this will be covered by #222 when I get around to it.

**Comment by madprops** [comment]
I think it's covered there, so I'm gonna close this
