### ISSUE TITLE
Ignore some players with playerctld

### ISSUE THREAD

**Issue by madprops** [altdesktop/playerctl#243]
I've had problems when I have a browser playing a video and a music player.

For instance:

1) Pause music player to start watching a youtube video
2) After that's done try to unpause music player after video ends
3) But the browser video player is now the active player
4) Not what you intended

I think maybe the issue is that I don't associate web video with playerctl.
Wondering if there's a way to make playerctl ignore some mpris players.
I would prefer to only have the active player bounce between my music players.

**Comment by acrisci** [comment]
Yes, playerctl will use the daemon when it is running automatically when no player is specified. You can use the player selector flags to filter the player you don't want to use.

**Comment by madprops** [comment]
Just realized there's a "-i" flag to ignore players, thanks.
