### ISSUE TITLE
SOLVED: How to offset position of currently playing track by -10 seconds?

### ISSUE THREAD

**Issue by ke-ss** [altdesktop/playerctl#244]
When listening to an audio book i'm setting up a hotkey to go back 10 secs from the current position if I miss something or need to hear it again for a fuller understanding.

The command  
`playerctl position offset -10`  
does nothing except produce this output on the command line  
`Unknown option -10`  

I have tried a number of possible variations of the `position offset` command and everything obvious to me fails.

What is the command to send a playing track back 10 seconds and then keep playing from there?

ps All other commands I have tried seem to work in the expected way.

**Comment by acrisci** [comment]
Check the manual. Use this: `playerctl position offset 10-`.

**Comment by ke-ss** [comment]
Thanks. That did not work but was really helpful becasue it suggested what did. Here is what does it
 `playerctl position 10-`
The only of the many variations I did not try was to put the `-` on the right hand side of the 10. That was not obvious.
Anyways, got there. Hopefully this will help someone else out

**Comment by ke-ss** [comment]
@acrisci great piece of code b.t.w. Thanks :)
