### ISSUE TITLE
How do I control volume in fixed increments/decrements?

### ISSUE THREAD

**Issue by Netherquark** [altdesktop/playerctl#246]
Hello. I'm using playerctl with [cunidev's "gestures" app](https://gitlab.com/cunidev/gestures) which relies on libinput. I'm using [Diffuse](nightly.diffuse.sh/) via Firefox on Manjaro (Gnome). I have assigned 4 finger swipe down to `playerctl play-pause` and 4 finger swipe left to `playerctl next` and right to `playerctl previous`. This works perfectly. But I also wanted to control volume variably via pinch in and out. ie, pinch in decreases and pinch out increases volume by a fixed amount. I tried using `playerctl volume 0.8 +` for starters, to see if I can atleast change it from any value to a fixed value but that isn't working. But assigning `playerctl play-pause` to the same gesture works, so the gesture itself is working. Which means my syntax is probably wrong. How can I make it so that pinching in decreases volume by 10%, while pinching out increases volume by 10% each time? Thanks in advance, this is a really cool program.

**Comment by acrisci** [comment]
`playerctl volume 0.10+` I believe does what you want. Not all players support volume, such as Spotify. Try it with VLC.

**Comment by Netherquark** [comment]
yeah.. firefox is showing this error:
Could not execute command: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code0: org.mpris.MediaPlayer2.Player:Volume setting is not supported

guess ill have to figure out how to use alsamixer for the same function. thanks anyways

**Comment by thiswillbeyourgithub** [comment]
Hi, I ended up creating a shell script that allows to modify the volume of spotify. It's to be used in my minimalist project that says aloud the name of the music playing on spotify using AI btw (repo here: https://github.com/thiswillbeyourgithub/Spotify_tts)


here's the code so far: (latest version in my repo)

```
#!/bin/zsh
# usage : ./script * 3    <- multiplies the volume by 3
#         ./script / 4   <- divides the volume by 4
#  there is a failsafe: the volume cannot be higher than 65536
#
# the snippet is originaly from there:     # awesome snippet found there: https://unix.stackexchange.com/questions/208784/command-line-per-application-volume-maybe-amixer-or-pactl
#
args=("$@")
sign=${args[1]}
factor=${args[2]}

app_name="spotify"
cur_vol=""
pactl list sink-inputs |while read line; do \
    sink_num_check=$(echo "$line" |sed -rn 's/^Sink Input #(.*)/\1/p')
    if [ "$sink_num_check" != "" ]; then
        current_sink_num="$sink_num_check"
    else
        app_name_check=$(echo "$line"  |sed -rn 's/application.name = "([^"]*)"/\1/p')
        if [ "$cur_vol" = "" ]; then
            cur_vol=$(echo "$line"  |sed -rn 's/Volume: front-left: (.*?) (.*)/\1/p' | awk '{print $1}')
        fi
        if [ "$app_name_check" = "$app_name" ]; then
            new_vol="$(($cur_vol$sign$factor))"
            new_vol=$((new_vol<65536 ? new_vol : 65536))
            pactl set-sink-input-volume "$current_sink_num" "$new_vol"
        fi
    fi
done

```

pinging other related issues: #239 #20 #156 #246

**Comment by flexiondotorg** [comment]
I was done something similar to @thiswillbeyourgithub to integrate Spotify with my OBS Studio streaming setup. However, I noticed that Spotify has recently been updated and can now be fully controlled using `playerctl`, including changing volume, position, loop and shuffle which previously didn't work 🥳
