### ISSUE TITLE
Celluloid does not work with playerctl when playerctld daemon is running

### ISSUE THREAD

**Issue by Nuromi-pm** [altdesktop/playerctl#250]
The player I am using is [Celluloid](https://celluloid-player.github.io/).
playerctl does not work with celluloid even though compatibility with mpris is enabled in the settings.
When run `playerctl --list-all` in terminal, I get `No players were found`.

I get the following error in journalctl when launching celluloid (sorry for the Spanish):
`playerctld[772]: could not get properties for active player: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No existe la interfaz «org.freedesktop.DBus.Properties» en el objeto en la ruta /org/mpris/MediaPlayer2`

mpv-mpris, firefox and clementine works fine.
OS: Debian 11 with xfce desktop.

**Comment by Nuromi-pm** [comment]
I found out that playerctl works with celluloid only when playerctld daemon is not running. If the playerctl daemon is running, it does not detect celluloid.

**Comment by acrisci** [comment]
I can reproduce this. Looking into it now.
