### ISSUE TITLE
playerctld daemon crash when opening a file within vlc

### ISSUE THREAD

**Issue by Nuromi-pm** [altdesktop/playerctl#251]
The player I am using is vlc.
When I open a video file from within the vlc window, either using the file picker or drag and drop, it causes playerctld daemon to crash. This does not happen when i open a file from the file manager (as long as vlc is not running).

I get the following message in journalctl when playerctld daemon crash
`traps: playerctld[25418] trap int3 ip:7f3d896e5ca7 sp:7fffef82bd30 error:0 in libglib-2.0.so.0.6600.8[7f3d896a9000+88000]`

OS: Debian 11 with xfce desktop.

**Comment by acrisci** [comment]
This should be fixed on the master branch.
