### ISSUE TITLE
volume -[whatever with "." as a comman] doesn't work: "Unknown Option -[given amount]"

### ISSUE THREAD

**Issue by evanescente-ondine** [altdesktop/playerctl#254]
I use audacious, but regardless the problelm is with playerctl. two terminals react the same so I doubt it's an issue of character escapement of whatever... I tried \- too and it reads the same.
playerctl version v2.4.1

uname -a:
Linux mehdi-80qr 5.14.11-arch1-1 #1 SMP PREEMPT Sun, 10 Oct 2021 00:48:26 +0000 x86_64 GNU/Linux

**Comment by acrisci** [comment]
As you have found, I cannot use `volume -0.5` because that looks like a short flag. Instead, the syntax is like `volume 0.5-`.

**Comment by evanescente-ondine** [comment]
Many thanks !
