### ISSUE TITLE
playerctl doesn't recognize mpd

### ISSUE THREAD

**Issue by Apopheosis** [altdesktop/playerctl#255]
The player I am using is mpd.

Playerctl works with spotify, but doesn't recognize mpd for some reason.

playerctl -l outputs "no players found"

dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1635719233.142468 sender=org.freedesktop.DBus -> destination=:1.6492 serial=3 reply_serial=2 outputs:

`   array [
      string "org.freedesktop.DBus"
      string ":1.4382"
      string ":1.7"
      string "org.freedesktop.systemd1"
      string ":1.4530"
      string ":1.4420"
      string ":1.4423"
      string "org.gtk.vfs.Daemon"
      string ":1.0"
      string ":1.4424"
      string "org.pulseaudio.Server"
      string "org.PulseAudio1"
      string "org.mpris.MediaPlayer2.playerctld"
      string ":1.6492"
      string ":1.4381"
   ]

**Comment by acrisci** [comment]
You need the mpd mpris plugin for it to work.

**Comment by Apopheosis** [comment]
Thanks, it works now, but mpd-mpris now occupies the whole terminal while working. Is it possible to make it start by default when using playerctl?

**Comment by acrisci** [comment]
Yeah look at their documentation.
