### ISSUE TITLE
Can no longer build with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Lenbok** [altdesktop/playerctl#258]
Unfortunately, it looks like #228 broke the ability to build on Ubuntu 20.04 LTS, since it ships with meson 0.53.2.

**Comment by acrisci** [comment]
Can you do `pip install meson`?

**Comment by Lenbok** [comment]
Right you are! I removed the system meson package and pip installed the latest -- all is good and sorry for the noise!
