### ISSUE TITLE
Following metadata of multiple defined players follows only the first one in the list

### ISSUE THREAD

**Issue by Ingvix** [altdesktop/playerctl#260]
The players I am using is mpd with mpDris2 and Spotify.

If player is not defined it follows all of them but, for example, with `--player=mpd,spotify` it follows only the first one.

**Comment by Ingvix** [comment]
Additionally even without defining `--player` it returns only one player's metadata right after launching the command, rather than outputting metadata from each player it follows.

**Comment by acrisci** [comment]
Try adding the `--all-players` flag.

**Comment by Ingvix** [comment]
Seems to work, though not the most intuitive thing to do. The second issue still stands though.

**Comment by acrisci** [comment]
It doesn't do that. This command was designed for status line generators in desktop bars and that might cause a flash of partially rendered content.

**Comment by Ingvix** [comment]
And I need them all to build the input line for my status bar. But I guess I can just run the command once without following at the beginning to get what I need. I feel that if a user wants to follow multiple players, they probably wants to know all of their tracks at the start but if you see it differently, I guess that's that.
