### ISSUE TITLE
play-pause not working with spotifyd (the pausing part)

### ISSUE THREAD

**Issue by Nicceboy** [altdesktop/playerctl#261]
I am not sure if [spotifyd](https://github.com/Spotifyd/spotifyd) is officially supported, but it works pretty well with playerctl.

However, there is one command `playerctl play-pause` which does not pause when attempting to pause the media. Also other variations are not working e.g. 
```console
─➤  G_MESSAGES_DEBUG=playerctl playerctl --player spotifyd play-pause
(playerctl:3131): playerctl-DEBUG: 02:22:35.285: Getting list of player names from D-Bus
(playerctl:3131): playerctl-DEBUG: 02:22:35.286: Playerctld is running. Getting names from there.
(playerctl:3131): playerctl-DEBUG: 02:22:35.286: Getting list of player names from D-Bus
(playerctl:3131): playerctl-DEBUG: 02:22:35.751: initializing player: spotifyd
```
Starting of playing works with the same command, and other commands I have tried so far.
Pausing works with `playerctl pause`

I'm using the latest package from Arch repository
```console
─➤  pacman -Qs playerctl
local/playerctl 2.4.1-1
    mpris media player controller and lib for spotify, vlc, audacious, bmp, xmms2, and others.
```

**Comment by pietryszak** [comment]
playerctl --player spotifyd play
playerctl --player spotifyd pause workig fine
playerctl play-pause not working for me.

And I think It's related with [Spotifyd Bug 1018](https://github.com/Spotifyd/spotifyd/issues/1018)

**Comment by Nicceboy** [comment]
Okay. It seems that we need to wait for upstream fix then!

**Comment by Nicceboy** [comment]
This is fixed on the upstream now.
