### ISSUE TITLE
Unknown or unsupported transport “disabled” for address “disabled:”

### ISSUE THREAD

**Issue by 144reasons** [altdesktop/playerctl#262]
The player I am using is Spotify.

I am trying to use `playerctl status`, but every time I try to run that, it gives me the following error:
`Unknown or unsupported transport “disabled” for address “disabled:”`
I thought it was an issue with the daemon, so I ran `playerctld daemon`, but got the following:
`could not connect to message bus: Unknown or unsupported transport ?disabled? for address ?disabled:?`

Did I install it incorrectly?

**Comment by acrisci** [comment]
It seems as though DBus is disabled on your system. You cannot use playerctl unless this is set up correctly.

**Comment by 144reasons** [comment]
Looking into it now, thank you!

**Comment by 144reasons** [comment]
This was user error, closing
