### ISSUE TITLE
playerctld maintains a list of players, but lacks an option to show that list

### ISSUE THREAD

**Issue by thomasvs** [altdesktop/playerctl#265]
I'm trying to figure out why playerctld is wrongly keeping my paused rhythmbox at the top of the stack over my playing spotify.

I see shift and unshift commands to move to a different player, but a list command to list all currently known players, and their order, seems like an easy addition?

**Comment by acrisci** [comment]
You can run playercltd with `G_MESSAGES_DEBUG=playerctl playerctld` and it will display debug messages that explains why it chooses the player it does.

**Comment by thomasvs** [comment]
Thanks for that!

Now, when running it, and pressing play in rhythmbox, I see

(playerctld:1181414): playerctl-ERROR **: 17:17:25.803: cannot update properties for unknown interface: org.mpris.MediaPlayer2.Playlists
Trace/breakpoint trap


That seems like a clearer reason for why it might not be working for me.  I'll open a separate issue.
