### ISSUE TITLE
volume will not increment past 0.06

### ISSUE THREAD

**Issue by theorytoe** [altdesktop/playerctl#271]
Player: mpd
I have used both the mpDris2 and mpd-mpris backends.

Issue:
when the current volume is less than 0.06, and you attempt to increase/increment the volume past that point 
(like `playerctl --player mpd volume 0.01+)`, nothing will change and the volume will stat constant.
This issue also happens at 0.57 volume.

This does not occur on any other players (notably ncspot and vlc).

**Comment by udf** [comment]
This doesn't look like a playerctl bug, by looking at the dbus messages with `dbus-monitor --session`, I see that playerctl is telling the mpris client to set its volume to 58%:

    method call time=1655513091.401890 sender=:1.175 -> destination=:1.121 serial=17 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=GetAll
      string "org.mpris.MediaPlayer2.Player"
    method return time=1655513091.402349 sender=:1.121 -> destination=:1.175 serial=2261 reply_serial=17
      array [
          # ...
          dict entry(
            string "Volume"
            variant             double 0.57
          )
          # ...
      ]

    method call time=1655513091.402547 sender=:1.175 -> destination=org.mpris.MediaPlayer2.mpd serial=18 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=Set
      string "org.mpris.MediaPlayer2.Player"
      string "Volume"
      variant       double 0.58

There's a `PropertiesChanged` message from mpd after that, but the volume doesn't get updated. Curiously, using `mpc` to increment the volume *does* cause it to increase (`mpc volume +1`).

Additionally, trying to set the volume directly to 58% (`playerctl --player mpd volume 0.58`) results in it being set to 57%, so something is interpreting 0.58 as 0.57 (perhaps its a rounding error). Setting the volume to 58% using mpc works as expected.

The issue also occurs using cantata's built-in mpris functionality. So it's either an issue with how 3 different mpris clients handle the dbus message (maybe a common library bug) or a bug in mpd itself (but then why does mpc work?).

More investigation is needed to find out where the double from dbus gets turned into an integer.

**Comment by udf** [comment]
Okay, wow it's actually a rounding issue in 3 different clients.

mpd-mpris has it fixed: https://github.com/natsukagami/mpd-mpris/pull/20
My mpDris pull request: https://github.com/eonpatapon/mpDris2/pull/157

Cantata is archived, so no chance of fixing it there.

@acrisci @Theory-of-Everything This issue can be closed.

**Comment by theorytoe** [comment]
alrighty!
