### ISSUE TITLE
Seeking is Not Always Precise

### ISSUE THREAD

**Issue by amarz45** [altdesktop/playerctl#280]
I am using the latest version of mpv and version 2.3.1 of playerctl. Most commands work perfectly. I want to seek forward by one second by using `playerctl position 1+`. This does not **always** work. Sometimes it seeks forward by one second, and sometimes it seeks forward by five or even 10 seconds. It is not consistent; it seems to be random.

**Comment by yue-dongchen** [comment]
Same issue with mpv, however it's consistently 5.12 seconds for me.

**Comment by yue-dongchen** [comment]
To isolate this as a playerctl issue, I tried two other players - GNOME Totem and Celluloid (mpv frontend with its own mpris2 implementation). The seeking has been reliable.

This has been reported to mpv-mpris: https://github.com/hoyon/mpv-mpris/issues/86
@amarakon You might want to close this.
