### ISSUE TITLE
Add option to mute and unmute

### ISSUE THREAD

**Issue by llyyr** [altdesktop/playerctl#291]
Currently I can do this with a bash script by storing the current volume, setting it to 0 then setting it back to the original value to unmute. It would be nice if playerctl supported a less hacky way of muting.

**Comment by veloek** [comment]
@llyyr I use `pactl` for mute/unmute:
```
pactl set-sink-mute @DEFAULT_SINK@ toggle
```

**Comment by llyyr** [comment]
But I don't want to mute everything, only my music player. My specific use case is listening to a live stream that takes 15-20 seconds for reconnect + buffer after resuming, so it's better to just mute instead of pause if I want to quickly listen to something else (like a Twitter clip for example) without waiting for reconnection.

**Comment by veloek** [comment]
I see. Well, it doesn't seem like the spec include mute/unmute, so playerctl would have to remember last volume, basically what you're already doing I guess..

https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html

**Comment by llyyr** [comment]
I wasn't aware this is a MPRIS limitation, closing this issue then
