### ISSUE TITLE
playerctl position does not work

### ISSUE THREAD

**Issue by lxwbr** [altdesktop/playerctl#30]
Looks like position argument is not working correctly with Spotify. 

```
user@ubuntu:~$ playerctl position 10
An error occurred: Could not get track id to set position
```

Though following works:

```
user@ubuntu:~$ playerctl metadata
{'mpris:trackid': <'spotify:track:3emundWeK0EWgGVU2tDzfs'>, ...
```

For reproduction:

```
user@ubuntu:~$ spotify --version
Spotify version 1.0.28.89.gf959d4ce, Copyright (c) 2016, Spotify Ltd
user@ubuntu:~$ playerctl --version
v0.5.0
```

I am using Ubuntu Server 16.04.

**Comment by ackl** [comment]
[Probably related to this as well ( ‎2012-05-03 )](https://community.spotify.com/t5/Desktop-Linux-Windows-Web-Player/Spotify-DBus-position-property-always-returns-0/td-p/54107) since `playerctl position` always returns 0 with Spotify.

**Comment by osense** [comment]
@ackl That link just returns access denied now

**Comment by acrisci** [comment]
I'm going to close this because it's an old issue. For spotify, please contact their customer support. Open a new issue if this still affects you with another player.
