### ISSUE TITLE
How to get album art / cover for currently playing song?

### ISSUE THREAD

**Issue by MihirGrand** [altdesktop/playerctl#309]
How to get album art or cover for currently playing song? Couldn't find anything about it in docs, or is the feature not supported?

**Comment by PassiveLemon** [comment]
`playerctl metadata mpris:artUrl` will return the url for the image. You can then use curl or wget to download it or something.

**Comment by MihirGrand** [comment]
> `playerctl metadata mpris:artUrl` will return the url for the image. You can then use curl or wget to download it or something.

That works, thanks!
