### ISSUE TITLE
duration(position) timer continues after pausing audio

### ISSUE THREAD

**Issue by mrsteve0924** [altdesktop/playerctl#315]
The player I am using is [PLAYER].
cVLC

i have a script i use to display "position | total time" in the my panel.  if i pause the song the timer continues counting up.  the counter stops when it reaches the length of the song.  

The audio is definitely paused though.  if i unpause then the counter goes back to the spot it was paused and song continues. 

i use this same script on xfce and it works fine.  been playing around with wayland with wayfire and this is where is see this issue. i've tried typing the playerctl commands directly into terminal and I get the same behavior

pausing audio from ncspot has no issues

maybe a dbus issue??  thanks for any help.

<details>

<summary>script</summary>

#!/bin/bash

tooltip=$(playerctl metadata --format '{{ artist }} - {{ title }}')

if [ "$(playerctl -i firefox,chromium status)" = "Playing" ]
then
	output=$(playerctl metadata --format '{{ trunc(artist,24) }} - {{ trunc(title,26) }}')
        output2=$(playerctl metadata --format '{{ duration(position) }} | {{ duration(mpris:length) }}')
else
if [ "$(playerctl -i firefox,chromium status)" = "Paused" ]
then	
	output=$(playerctl metadata --format '{{ trunc(artist,24) }} - {{ trunc(title,26) }}')
	output2=$(playerctl metadata --format '{{ duration(position) }} | {{ duration(mpris:length) }}  {{ uc(status) }}')
else
	output=""

fi
fi

echo $output
echo $output2

</details>

panel output.  i know you cant see the counter continue. if i need to upload a video i will.
![2023-08-03_17:37:23](https://github.com/altdesktop/playerctl/assets/37476191/ab3e95c7-2a65-49f8-9d0b-27c2a4ff14c6)

**Comment by mrsteve0924** [comment]
after many updates to wayfire since i reported this issue, it looks like pause now works correctly.  

hooray for me.  

consider issue closed

**Comment by danielwerg** [comment]
I'm having this issue right now with firefox.

**Comment by snatchr** [comment]
> I'm having this issue right now with firefox.

same here
