### ISSUE TITLE
No D-Bus interface with Spotify

### ISSUE THREAD

**Issue by eyalch** [altdesktop/playerctl#55]
I went over some of the issues here and noticed that there's a problem with Spotify itself providing the D-Bus interface. Is this problem still relevant?

Output of:
```
$ dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1515162666.148629 sender=org.freedesktop.DBus -> destination=:1.3 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.3"
      string "org.gnome.Terminal"
      string ":1.1"
   ]
```

My original problem is with Spotify but I decided to try other media players with support for MPRIS D-Bus, so I tried [Clementine](https://www.clementine-player.org/). Still no players with `playerctl -l`.

I'm happy to provide any other needed outputs.

**Comment by acrisci** [comment]
Unfortunately, the dbus interface of spotify is not well maintained. It comes and goes with the versions.

I can get clementine to give me the dbus interface with the default install.

You seem to be a little light on dbus names, but that's the only thing that looks weird about your output. I'm not really sure what is going on. Does it work with vlc?

**Comment by eyal0803** [comment]
Since my luck isn't at it's best at the moment, what am I **exactly** supposed to do?

1. Install VLC (`pacman -S vlc` for me)
2. Open VLC
3. Run `playerctl -l`

Is that it?

**Comment by acrisci** [comment]
Yeah that should work.

**Comment by eyal0803** [comment]
Didn't work.

**Comment by Navgeet** [comment]
This might help: https://www.reddit.com/r/artixlinux/comments/hr2qgj/spotify_not_connecting_to_dbusmpris/g07n3jg?utm_source=share&utm_medium=web2x

**Comment by acrisci** [comment]
See the troubleshooting section of the readme for instructions how to fix this.
