### ISSUE TITLE
Conection to player Failed: No players Found 

### ISSUE THREAD

**Issue by MakeProjects** [altdesktop/playerctl#87]
Hi my name is David, 

I tried to execute playerctl in different linux os, Ubuntu 18.04 and Xubuntu 18.04 64bits but always got **Conection To player Failed: No players Found.** 

1º I´ve installed VLC via APT from CLI 
2º I´ve Intalled playerctl-0.6.1.deb from the different manager Packages
3º I execute playerctl -l, and I got No players Found. 

I tried to install SMplayer too, but I got the same. 

What can I do?

Thanks.

**Comment by jgonsior** [comment]
I'm using Ubuntu 18.04 as well, and it's not in this dbus list. That means we just have to wait until the DBUS interface appears again in the Spotify app?

**Comment by acrisci** [comment]
I can get it to work on ubuntu 18.04 with all the default settings.

Note that spotify requires the environment variable `DBUS_SESSION_BUS_ADDRESS` to be set. That's set by the session manager.

```
$ echo $DBUS_SESSION_ADDRESS
> path=/run/user/1000/bus
```

If you're using `xinit`, follow the instructions in the new [troubleshooting section](https://github.com/acrisci/playerctl#troubleshooting).

**Comment by Vaishnavikumara** [comment]
@acrisci  , I am trying to integrate Alexa with mps-youtube to play videos on voice command. When I am running the scriptfile for mps-youtube manually from the terminal , the player is getting detected , where as , if I try to control the script with alexa, the player is not getting detected . Kindly help.

**Comment by acrisci** [comment]
I'm going to close this because it's an old issue. If you still have this problem, open a new issue.
